---
#title: "cover_letter"
output: html_document
#date: "2023-12-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Cover letter -->
<!-- Authors should provide a cover letter that includes the affiliation and contact information for the corresponding author. Authors should briefly discuss the work's importance and explain why the work is considered appropriate for the diverse readership of Nature Communications. Authors are asked to provide the names and contact information for qualified scientific reviewers and they may request the exclusion of certain referees. Finally, authors should indicate whether they have had any prior discussions with Nature Communications editor about the work described in the manuscript. -->

I am writing to submit the manuscript, **"Female reproductive status and ecological conditions impact the magnitude of sex differences in human immune status across the lifespan"** to Nature Communications, co-authored with Michael Gurven, Benjamin Trumble, Jonathan Stieglitz, Daniel Eid Rodriguez, Ivan Maldonado Suarez, Hillard Kaplan, Aaron Blackwell, and Amy Boddy. 

Current research indicates that there are substantial differences in male and female immune function and disease risk, with women experiencing less infectious disease risk but making up roughly 80% of all autoimmune diagnoses. However, because past research has predominantly focused on heavily industrialized populations with relatively low fertility rates and has generally excluded pregnant and postpartum women, it is unclear how female reproduction shapes sexual dimorphism across the lifespan or how these effects vary based on ecological factors. 

Here, we test the hypothesis that evolutionarily novel conditions common to industrialized populations (e.g., energetic excess, reduced parity) amplify evolved sex differences in immunity. Using data from the Tsimane Health and Life History Project (n = 5,866) and the US Center for Disease Control’s NHANES dataset (n = 9,825), we estimate and compare the age-specific effects of sex on immune cell counts and neutrophil-to-lymphocyte ratio among the Tsimane, a non-industrialized South American Indigenous population, and a representative sample from the USA. 

Compared to the USA, we find that the magnitude of sexual dimorphism in immune measures across the lifespan is significantly lower among the Tsimane and that this pattern is primarily driven by population-specific effects of pregnancy on female immune status. Our results suggest that the discrepancy in autoimmune disease risk between men and women found in industrialized high-income countries may be due, in part, to an exaggerated inflammatory response during pregnancy and population-level shifts in reproductive strategies (e.g., delayed age at first birth, reduced parity).  
 
We believe our paper is ideally suited to the diverse readership and high impact of Nature Communications. Our paper is timely, given the call to investigate the effects of ecological conditions on sex differences in health and disease (Natri et al., 2019) and complementary research on mechanisms of sexual dimorphism in immune function (including in Nature Communications: *Gupta et al. 2020; Huang et al. 2021; Dobson et al. 2026*). Furthermore, the results communicated in our paper are relevant across a wide range of disciplines, including evolutionary biology, anthropology, medicine, ecology, and population biology.
 
Currently there are 2 primary figures and 2 primary tables. The manuscript also includes a link to a public GitHub repository containing all R code used in our analyses. The Supplementary Information (SI) file contains 2 additional figures, 5 additional tables. 
 
Suggested Reviewers:\
* Christopher Kuzawa \
* Thomas McDade \
* Elizabeth Miller, University of South Florida, emm3@usf.edu \ 
* J. Lee Nelson, Fred Hutchinson Cancer Research Center, nelsonlab@fredhutch.org \
* Andrea Graham, Princeton University, algraham@princeton.edu \
 
Thank you for your time and consideration!
 
Sincerely,

Carmen Hove, PhD (corresponding author) \
University of California, Santa Barbara \
Integrative Anthropological Sciences Unit \

Amy Boddy, PhD (senior author) \
University of California, Santa Barbara \
Integrative Anthropological Sciences Unit \




 



